using System.Collections.Generic;
using System;
using Pulumi;
using Pulumi.AzureNative.Resources;
using Pulumi.AzureNative.OperationalInsights;
using Pulumi.AzureNative.ApplicationInsights;
using Pulumi.AzureNative.ContainerRegistry;
using Pulumi.AzureNative.ContainerRegistry.Inputs;
using Pulumi.AzureNative.App;
using Pulumi.AzureNative.App.Inputs;
using Pulumi.AzureNative.Web;
using Pulumi.AzureNative.Web.Inputs;
using Pulumi.AzureNative.Sql;
using Pulumi.AzureNative.Sql.Inputs;
using Pulumi.AzureNative.KeyVault;
using Pulumi.AzureNative.KeyVault.Inputs;
using Pulumi.AzureNative.AppConfiguration;
using Pulumi.AzureNative.ManagedIdentity;
using Pulumi.AzureNative.Authorization;
using System.Linq;

return await Pulumi.Deployment.RunAsync(() =>
{
    var config = new Pulumi.Config();
    var location = config.Get("location") ?? "eastus";
    var environment = config.Get("environment") ?? "dev";
    var sqlAdminLogin = config.Get("sqlAdminLogin") ?? "sqladmin";
    var sqlAdminPassword = config.RequireSecret("sqlAdminPassword");
    
    // App Name for naming standards
    var appName = config.Get("appName") ?? "hotshot";

    // Helper function for naming standard: {slug}-{environment}-{region}-{appName}
    // Includes truncation logic for length-restricted resources (Key Vault, Storage)
    string GetResourceName(string slug, string separator = "-", int maxLength = 0)
    {
        string name;
        
        string BuildName(string loc)
        {
             if (separator == "")
            {
                return $"{slug}{environment}{loc}{appName}".ToLowerInvariant();
            }
            else
            {
                return $"{slug}{separator}{environment}{separator}{loc}{separator}{appName}";
            }
        }

        name = BuildName(location);

        // Enforce length limits if specified
        if (maxLength > 0 && name.Length > maxLength)
        {
            // Strategy 1: Truncate the appName first
            var fixedPart = separator == "" 
                ? $"{slug}{environment}{location}"
                : $"{slug}{separator}{environment}{separator}{location}{separator}";
                
            var availableSpace = maxLength - fixedPart.Length;

            // If space is too tight (less than 3 chars for app name), try using short region code
            if (availableSpace < 3)
            {
                string shortRegion = location switch
                {
                    "eastus" => "eus",
                    "eastus2" => "eus2",
                    "centralus" => "cus",
                    "northcentralus" => "ncus",
                    "southcentralus" => "scus",
                    "westcentralus" => "wcus",
                    "westus" => "wus",
                    "westus2" => "wus2",
                    "westus3" => "wus3",
                    _ => location // No abbreviation defined
                };

                // Re-calculate with short region
                fixedPart = separator == "" 
                    ? $"{slug}{environment}{shortRegion}"
                    : $"{slug}{separator}{environment}{separator}{shortRegion}{separator}";
                
                availableSpace = maxLength - fixedPart.Length;
                
                // If still no space, we have to fail or truncate aggressively
                if (availableSpace < 2)
                {
                     throw new InvalidOperationException($"Generated name prefix '{fixedPart}' is too long for resource with limit {maxLength}. Cannot append appName.");
                }
            }

            var truncatedAppName = appName.Length > availableSpace 
                ? appName.Substring(0, availableSpace) 
                : appName;
                
            name = fixedPart + truncatedAppName;
            
            // Final check
            if (name.Length > maxLength)
            {
                 throw new InvalidOperationException($"Unable to satisfy length limit {maxLength} for resource '{name}'.");
            }
            
            Pulumi.Log.Warn($"Resource name '{name}' was truncated to fit {maxLength} character limit.");
        }

        return name;
    }

    // Compute the expected Container App and Static Web App FQDNs
    // These follow Azure's naming conventions and can be predicted before resource creation
    // Note: Container App Environment suffix is generated by Azure, we can't fully predict the FQDN until the environment is created, 
    // but the name input follows our standard.
    // The previous logic assumed a specific FQDN format which might change with the new naming.
    // For now, we will update the resource names and let the outputs provide the FQDNs.

    var staticWebAppRegion = location == "eastus2" ? "eastus2" : "centralus"; // Static Web Apps have limited regions
    var staticWebAppName = GetResourceName("swa");
    
    // Azure AD Tenant ID is required for Key Vault access policies
    // Get from: az account show --query tenantId -o tsv
    var azureTenantId = config.Require("azureTenantId");
    // Azure Subscription ID is required for role assignments
    // Get from: az account show --query id -o tsv
    var subscriptionId = config.Require("subscriptionId");
    // Container image name (without registry prefix). Default: hotshot-api
    // The full image path will be constructed as: <registry>.azurecr.io/<imageName>:<imageTag>
    var imageName = config.Get("imageName") ?? "hotshot-api";
    var imageTag = config.Get("imageTag") ?? "latest";
    // Container Job image name (defaulting to a separate repo or same one depending on build strategy)
    var jobImageName = config.Get("jobImageName") ?? "hotshot-db-migration-job";
    var jobImageTag = config.Get("jobImageTag") ?? "latest";
    // Set to true to use a placeholder image for initial deployment before pushing your own image
    var usePlaceholderImage = config.GetBoolean("usePlaceholderImage") ?? false;
    // SQL firewall allowed IP ranges (comma-separated). If not specified, defaults to Azure services only (0.0.0.0)
    // For production, specify known IP ranges or use private endpoints instead
    var sqlAllowedIpRanges = config.Get("sqlAllowedIpRanges") ?? "0.0.0.0";
    
    // Azure AD B2C / Entra External ID configuration for API authentication
    // These must be configured in Pulumi config or the API will fail to start
    // We prioritize Environment Variables (from GitHub Secrets) over Pulumi Config
    var azureAdB2cInstance = Environment.GetEnvironmentVariable("AZURE_AD_B2C_INSTANCE") ?? config.Get("azureAdB2cInstance") ?? "";

    // FIX: Ensure Instance is a valid URL (if user provided just "Palfery", convert to "https://Palfery.b2clogin.com")
    if (!string.IsNullOrEmpty(azureAdB2cInstance) && !azureAdB2cInstance.StartsWith("http"))
    {
        var fixedInstance = $"https://{azureAdB2cInstance}.b2clogin.com";
        Pulumi.Log.Info($"Correcting AzureAdB2C Instance from '{azureAdB2cInstance}' to '{fixedInstance}'");
        azureAdB2cInstance = fixedInstance;
    }

    var azureAdB2cClientId = Environment.GetEnvironmentVariable("AZURE_AD_B2C_CLIENT_ID") ?? config.Get("azureAdB2cClientId") ?? "";
    var azureAdB2cDomain = Environment.GetEnvironmentVariable("AZURE_AD_B2C_DOMAIN") ?? config.Get("azureAdB2cDomain") ?? "";
    var azureAdB2cTenantId = Environment.GetEnvironmentVariable("AZURE_AD_B2C_TENANT_ID") ?? config.Get("azureAdB2cTenantId") ?? "";
    var azureAdB2cAudience = Environment.GetEnvironmentVariable("AZURE_AD_B2C_AUDIENCE") ?? config.Get("azureAdB2cAudience") ?? "";

    // Resource Group
    var resourceGroupName = GetResourceName("rg");
    var resourceGroup = new ResourceGroup(resourceGroupName, new ResourceGroupArgs
    {
        ResourceGroupName = resourceGroupName,
        Location = location,
        Tags = new InputMap<string>
        {
            { "Environment", environment },
            { "Project", "HotshotLogistics" },
            { "ManagedBy", "Pulumi" }
        }
    });

    // Log Analytics Workspace
    var workspace = new Workspace(GetResourceName("log"), new WorkspaceArgs
    {
        ResourceGroupName = resourceGroup.Name,
        Location = location,
        RetentionInDays = 30,
        Tags = new InputMap<string>
        {
            { "Environment", environment },
            { "Project", "HotshotLogistics" }
        }
    });

    // Retrieve the Log Analytics Workspace shared keys
    // We include resourceGroup.Id and workspace.Id in the tuple to ensure the resources are fully created before invoking GetSharedKeys
    var workspaceSharedKeys = Output.Tuple(resourceGroup.Name, workspace.Name, resourceGroup.Id, workspace.Id).Apply(t =>
        GetSharedKeys.InvokeAsync(new GetSharedKeysArgs
        {
            ResourceGroupName = t.Item1,
            WorkspaceName = t.Item2
        }));

    var workspaceSharedKey = Output.CreateSecret(workspaceSharedKeys.Apply(k => k.PrimarySharedKey ?? ""));

    // Application Insights Component
    var appInsights = new Component(GetResourceName("appi"), new ComponentArgs
    {
        ResourceGroupName = resourceGroup.Name,
        Location = location,
        ApplicationType = "web",
        Kind = "web",
        WorkspaceResourceId = workspace.Id,
        Tags = new InputMap<string>
        {
            { "Environment", environment },
            { "Project", "HotshotLogistics" }
        }
    });

    var appInsightsInstrumentationKey = appInsights.InstrumentationKey;
    var appInsightsConnectionString = appInsights.ConnectionString;

    // Managed Identity for Container App
    // This identity is used for authentication with Container Registry instead of admin credentials
    var containerAppIdentityName = GetResourceName("id");
    var containerAppIdentity = new UserAssignedIdentity(containerAppIdentityName, new UserAssignedIdentityArgs
    {
        ResourceName = containerAppIdentityName,
        ResourceGroupName = resourceGroup.Name,
        Location = location,
        Tags = new InputMap<string>
        {
            { "Environment", environment },
            { "Project", "HotshotLogistics" }
        }
    });

    // Container Registry with AdminUserEnabled DISABLED for enhanced security
    // ACR names must be alphanumeric only, max 50 chars
    var registryName = GetResourceName("cr", "", 50);
    var registry = new Registry(registryName, new RegistryArgs
    {
        RegistryName = registryName,
        ResourceGroupName = resourceGroup.Name,
        Location = location,
        Sku = new Pulumi.AzureNative.ContainerRegistry.Inputs.SkuArgs
        {
            Name = "Standard"
        },
        AdminUserEnabled = false, // SECURITY: Disabled admin user - use managed identity instead
        Tags = new InputMap<string>
        {
            { "Environment", environment },
            { "Project", "HotshotLogistics" }
        }
    });

    // Assign AcrPull role to managed identity for registry access
    // This allows the container app to pull images without admin credentials
    // AcrPull role definition ID: 7f951dda-4ed3-4680-a7ca-43fe172d538d
    var acrPullRoleDefinitionId = $"/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/roleDefinitions/7f951dda-4ed3-4680-a7ca-43fe172d538d";

    var acrPullRoleAssignment = new RoleAssignment($"ra-acr-pull-{environment}", new RoleAssignmentArgs
    {
        PrincipalId = containerAppIdentity.PrincipalId,
        PrincipalType = Pulumi.AzureNative.Authorization.PrincipalType.ServicePrincipal,
        RoleDefinitionId = acrPullRoleDefinitionId,
        Scope = registry.Id
    });

    // Azure Key Vault for secrets (using access policies - can't switch existing vault to RBAC)
    // KeyVault has 24 char limit
    var keyVaultName = GetResourceName("kv", "-", 24);
    var keyVault = new Vault(keyVaultName, new VaultArgs
    {
        VaultName = keyVaultName,
        ResourceGroupName = resourceGroup.Name,
        Location = location,
        Properties = new VaultPropertiesArgs
        {
            TenantId = azureTenantId,
            Sku = new Pulumi.AzureNative.KeyVault.Inputs.SkuArgs
            {
                Family = "A",
                Name = Pulumi.AzureNative.KeyVault.SkuName.Standard
            },
            AccessPolicies = new[]
            {
                new AccessPolicyEntryArgs
                {
                    TenantId = azureTenantId,
                    ObjectId = containerAppIdentity.PrincipalId,
                    Permissions = new PermissionsArgs
                    {
                        Secrets = new InputList<Pulumi.Union<string, Pulumi.AzureNative.KeyVault.SecretPermissions>>
                        {
                            Pulumi.AzureNative.KeyVault.SecretPermissions.Get,
                            Pulumi.AzureNative.KeyVault.SecretPermissions.List
                        }
                    }
                }
            },
            EnabledForDeployment = true,
            EnabledForTemplateDeployment = true
        },
        Tags = new InputMap<string>
        {
            { "Environment", environment },
            { "Project", "HotshotLogistics" }
        }
    }, new CustomResourceOptions
    {
        CustomTimeouts = new CustomTimeouts
        {
            Create = TimeSpan.FromMinutes(20),
            Update = TimeSpan.FromMinutes(20),
            Delete = TimeSpan.FromMinutes(20)
        }
    });

    // Azure App Configuration for non-secret configuration
    // Note: Free tier can take 5-10 minutes to provision and doesn't support soft delete
    var appConfigName = GetResourceName("appcs");
    var appConfig = new ConfigurationStore(appConfigName, new ConfigurationStoreArgs
    {
        ConfigStoreName = appConfigName,
        ResourceGroupName = resourceGroup.Name,
        Location = location,
        Sku = new Pulumi.AzureNative.AppConfiguration.Inputs.SkuArgs
        {
            Name = "free"
        },
        SoftDeleteRetentionInDays = 0, // Disable soft delete for free tier
        Tags = new InputMap<string>
        {
            { "Environment", environment },
            { "Project", "HotshotLogistics" }
        }
    }, new CustomResourceOptions
    {
        CustomTimeouts = new CustomTimeouts
        {
            Create = TimeSpan.FromMinutes(15)
        }
    });

    // App Configuration Data Reader role for managed identity (516239f1-63e1-4d78-a4de-a74fb236a071)
    var appConfigDataReaderRoleId = $"/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/roleDefinitions/516239f1-63e1-4d78-a4de-a74fb236a071";
    var appConfigRoleAssignment = new RoleAssignment($"ra-appconfig-reader-{environment}", new RoleAssignmentArgs
    {
        PrincipalId = containerAppIdentity.PrincipalId,
        PrincipalType = Pulumi.AzureNative.Authorization.PrincipalType.ServicePrincipal,
        RoleDefinitionId = appConfigDataReaderRoleId,
        Scope = appConfig.Id
    });

    // Azure AD B2C Configuration Keys in App Configuration
    var b2cConfigKeys = new Dictionary<string, string>
    {
        { "AzureAdB2C:Instance", azureAdB2cInstance },
        { "AzureAdB2C:ClientId", azureAdB2cClientId },
        { "AzureAdB2C:Domain", azureAdB2cDomain },
        { "AzureAdB2C:TenantId", azureAdB2cTenantId },
        { "AzureAdB2C:Audience", azureAdB2cAudience }
    };

    foreach (var key in b2cConfigKeys)
    {
        // Only create the key if a value is provided
        if (!string.IsNullOrEmpty(key.Value))
        {
            // Slugify the key name for the resource name (replace : with -)
            var resourceName = $"cfg-{key.Key.Replace(":", "-").ToLower()}-{environment}";
            
            var configKey = new KeyValue(resourceName, new KeyValueArgs
            {
                ResourceGroupName = resourceGroup.Name,
                ConfigStoreName = appConfig.Name,
                KeyValueName = key.Key,
                Value = key.Value,
                Tags = new InputMap<string>
                {
                    { "Environment", environment },
                    { "Project", "HotshotLogistics" }
                }
            });
        }
    }

    // SQL Server
    var sqlServerName = GetResourceName("sql");
    var sqlServer = new Server(sqlServerName, new ServerArgs
    {
        ServerName = sqlServerName,
        ResourceGroupName = resourceGroup.Name,
        Location = location,
        AdministratorLogin = sqlAdminLogin,
        AdministratorLoginPassword = sqlAdminPassword,
        Version = "12.0",
        MinimalTlsVersion = "1.2",
        PublicNetworkAccess = "Enabled",
        Tags = new InputMap<string>
        {
            { "Environment", environment },
            { "Project", "HotshotLogistics" }
        }
    }, new CustomResourceOptions
    {
        CustomTimeouts = new CustomTimeouts
        {
            Create = TimeSpan.FromMinutes(30),
            Update = TimeSpan.FromMinutes(30)
        }
    });

    // SQL Database
    var databaseName = GetResourceName("sqldb");
    var database = new Database(databaseName, new DatabaseArgs
    {
        DatabaseName = databaseName,
        ResourceGroupName = resourceGroup.Name,
        Location = location,
        ServerName = sqlServer.Name,
        Sku = new Pulumi.AzureNative.Sql.Inputs.SkuArgs
        {
            Name = "S0",
            Tier = "Standard"
        },
        MaxSizeBytes = 2147483648, // 2GB
        Tags = new InputMap<string>
        {
            { "Environment", environment },
            { "Project", "HotshotLogistics" }
        }
    });

    // Firewall rule to allow Azure services or specified IP ranges
    // NOTE: 0.0.0.0 is a special rule that allows Azure services to access the server
    // For production environments, consider using private endpoints or restricting to known IP ranges
    var firewallRules = new List<FirewallRule>();
    var ipRanges = sqlAllowedIpRanges.Split(',');
    for (int i = 0; i < ipRanges.Length; i++)
    {
        var ipRange = ipRanges[i].Trim();
        var ruleName = ipRange == "0.0.0.0"
            ? $"sqlfw-azure-services-{environment}"
            : $"sqlfw-allowed-{i}-{environment}";

        firewallRules.Add(new FirewallRule(ruleName, new FirewallRuleArgs
        {
            ResourceGroupName = resourceGroup.Name,
            ServerName = sqlServer.Name,
            StartIpAddress = ipRange,
            EndIpAddress = ipRange
        }));
    }

    // Build connection string (marked as secret to prevent exposure in state)
    var connectionString = Output.CreateSecret(
        Output.Tuple(sqlServer.FullyQualifiedDomainName, database.Name, sqlAdminPassword)
            .Apply(t => $"Server=tcp:{t.Item1},1433;Initial Catalog={t.Item2};Persist Security Info=False;User ID={sqlAdminLogin};Password={t.Item3};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"));

    // Container Apps Environment (Consumption only - Workload Profiles v2)
    var managedEnvironmentName = GetResourceName("cae");
    var managedEnvironment = new ManagedEnvironment(managedEnvironmentName, new ManagedEnvironmentArgs
    {
        EnvironmentName = managedEnvironmentName,
        ResourceGroupName = resourceGroup.Name,
        Location = location,
        AppLogsConfiguration = new Pulumi.AzureNative.App.Inputs.AppLogsConfigurationArgs
        {
            Destination = "log-analytics",
            LogAnalyticsConfiguration = new Pulumi.AzureNative.App.Inputs.LogAnalyticsConfigurationArgs
            {
                CustomerId = workspace.CustomerId,
                SharedKey = workspaceSharedKey
            }
        },
        WorkloadProfiles = new[]
        {
            new WorkloadProfileArgs
            {
                Name = "Consumption",
                WorkloadProfileType = "Consumption"
            }
        },
        Tags = new InputMap<string>
        {
            { "Environment", environment },
            { "Project", "HotshotLogistics" }
        }
    });

    // Container App Job (DB Migration)
    var migrationJobName = GetResourceName("caj");
    var migrationJob = new Pulumi.AzureNative.App.Job(migrationJobName, new Pulumi.AzureNative.App.JobArgs
    {
        JobName = migrationJobName,
        ResourceGroupName = resourceGroup.Name,
        Location = location,
        EnvironmentId = managedEnvironment.Id,
        Identity = new Pulumi.AzureNative.App.Inputs.ManagedServiceIdentityArgs
        {
            Type = "UserAssigned",
            UserAssignedIdentities = new InputList<string>
            {
                containerAppIdentity.Id
            }
        },
        Configuration = new JobConfigurationArgs
        {
            TriggerType = "Manual",
            ReplicaTimeout = 1800, // 30 minutes timeout
            // RetryLimit removed - it seems it's not a direct property of JobConfigurationArgs in this version or needs specific placement
            Registries = new[]
            {
                new RegistryCredentialsArgs
                {
                    Server = registry.LoginServer,
                    Identity = containerAppIdentity.Id
                }
            },
            Secrets = new[]
            {
                new Pulumi.AzureNative.App.Inputs.SecretArgs
                {
                    Name = "db-connection-string",
                    Value = connectionString
                }
            },
            ManualTriggerConfig = new JobConfigurationManualTriggerConfigArgs
            {
                Parallelism = 1,
                ReplicaCompletionCount = 1
            }
        },
        Template = new JobTemplateArgs
        {
            Containers = new[]
            {
                new ContainerArgs
                {
                    Name = "migration-job",
                    Image = usePlaceholderImage
                        ? "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
                        : registry.LoginServer.Apply(server => $"{server}/{jobImageName}:{jobImageTag}"),
                    Resources = new ContainerResourcesArgs
                    {
                        Cpu = 0.5,
                        Memory = "1Gi"
                    },
                    Env = new[]
                    {
                        new EnvironmentVarArgs
                        {
                            Name = "DB_CONNECTION_STRING",
                            SecretRef = "db-connection-string"
                        },
                        new EnvironmentVarArgs
                        {
                            Name = "ASPNETCORE_ENVIRONMENT",
                            Value = "Production"
                        }
                    }
                }
            }
        },
        Tags = new InputMap<string>
        {
            { "Environment", environment },
            { "Project", "HotshotLogistics" }
        }
    }, new CustomResourceOptions
    {
        DependsOn = { acrPullRoleAssignment },
        IgnoreChanges = new List<string> { "template.containers[*].image" }
    });

    // Static Web App (Next.js Admin Dashboard) - declared before Container App for CORS reference
    // staticWebAppName is already defined at the top of the file
    var staticWebApp = new StaticSite(staticWebAppName, new StaticSiteArgs
    {
        Name = staticWebAppName,
        ResourceGroupName = resourceGroup.Name,
        Location = staticWebAppRegion,
        Sku = new SkuDescriptionArgs
        {
            Name = "Free",
            Tier = "Free"
        },
        BuildProperties = new StaticSiteBuildPropertiesArgs
        {
            AppLocation = "1-Presentation/admin-dashboard",
            OutputLocation = "out",
            AppBuildCommand = "npm run build"
        },
        Tags = new InputMap<string>
        {
            { "Environment", environment },
            { "Project", "HotshotLogistics" }
        }
    });

    // Container App (API) with Managed Identity authentication
    var containerAppName = GetResourceName("ca");
    var containerApp = new ContainerApp(containerAppName, new ContainerAppArgs
    {
        ContainerAppName = containerAppName,
        ResourceGroupName = resourceGroup.Name,
        Location = location,
        ManagedEnvironmentId = managedEnvironment.Id,
        // SECURITY: Attach managed identity to container app for secure registry access
        Identity = new Pulumi.AzureNative.App.Inputs.ManagedServiceIdentityArgs
        {
            Type = "UserAssigned",
            UserAssignedIdentities = new InputList<string>
            {
                containerAppIdentity.Id
            }
        },
        Configuration = new ConfigurationArgs
        {
            Ingress = new IngressArgs
            {
                External = true,
                TargetPort = 8080,
                Transport = "auto",
                Traffic = new[]
                {
                    new TrafficWeightArgs
                    {
                        LatestRevision = true,
                        Weight = 100
                    }
                },
                AllowInsecure = false
            },
            // SECURITY: Registry credentials now obtained from Key Vault via managed identity
            // No longer storing plaintext credentials in Pulumi state
            Registries = new[]
            {
                new RegistryCredentialsArgs
                {
                    Server = registry.LoginServer,
                    Identity = containerAppIdentity.Id
                    // Removed Username and PasswordSecretRef - using managed identity instead
                }
            },
            Secrets = new[]
            {
                new Pulumi.AzureNative.App.Inputs.SecretArgs
                {
                    Name = "db-connection-string",
                    Value = connectionString
                },
                new Pulumi.AzureNative.App.Inputs.SecretArgs
                {
                    Name = "appinsights-connection-string",
                    Value = appInsightsConnectionString
                }
                // Removed registry-password secret - no longer needed with managed identity
            }
        },
        Template = new TemplateArgs
        {
            Containers = new[]
            {
                new ContainerArgs
                {
                    Name = "hotshot-api",
                    // Dynamically construct the container image path:
                    // - If usePlaceholderImage=true: use Microsoft's hello-world image for initial deployment
                    // - Otherwise: use <registry>.azurecr.io/<imageName>:<imageTag>
                    Image = usePlaceholderImage
                        ? "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
                        : registry.LoginServer.Apply(server => $"{server}/{imageName}:{imageTag}"),
                    Resources = new ContainerResourcesArgs
                    {
                        Cpu = 0.5,
                        Memory = "1Gi"
                    },
                    Env = new[]
                    {
                        new EnvironmentVarArgs
                        {
                            Name = "ASPNETCORE_ENVIRONMENT",
                            Value = "Production"
                        },
                        new EnvironmentVarArgs
                        {
                            Name = "ASPNETCORE_URLS",
                            Value = "http://+:8080"
                        },
                        // Azure App Configuration endpoint - app loads config from here
                        new EnvironmentVarArgs
                        {
                            Name = "AppConfiguration__Endpoint",
                            Value = appConfig.Endpoint
                        },
                        // Azure AD B2C Configuration
                        // Passed as environment variables to ensure the app starts even if App Configuration is delayed
                        new EnvironmentVarArgs { Name = "AzureAdB2C__Instance", Value = azureAdB2cInstance },
                        new EnvironmentVarArgs { Name = "AzureAdB2C__ClientId", Value = azureAdB2cClientId },
                        new EnvironmentVarArgs { Name = "AzureAdB2C__Domain", Value = azureAdB2cDomain },
                        new EnvironmentVarArgs { Name = "AzureAdB2C__TenantId", Value = azureAdB2cTenantId },
                        new EnvironmentVarArgs { Name = "AzureAdB2C__Audience", Value = azureAdB2cAudience },
                        // Key Vault URI - for secrets referenced from App Configuration
                        new EnvironmentVarArgs
                        {
                            Name = "KeyVault__VaultUri",
                            Value = keyVault.Properties.Apply(p => p.VaultUri)
                        },
                        // Managed Identity Client ID - for authenticating to App Config and Key Vault
                        new EnvironmentVarArgs
                        {
                            Name = "Azure__ManagedIdentityClientId",
                            Value = containerAppIdentity.ClientId
                        },
                        // Bootstrap secrets (until migrated to Key Vault)
                        new EnvironmentVarArgs
                        {
                            Name = "ConnectionStrings__DefaultConnection",
                            SecretRef = "db-connection-string"
                        },
                        new EnvironmentVarArgs
                        {
                            Name = "APPLICATIONINSIGHTS_CONNECTION_STRING",
                            SecretRef = "appinsights-connection-string"
                        },
                        new EnvironmentVarArgs
                        {
                            Name = "AllowedHosts",
                            Value = "*"
                        },
                        // CORS - computed from Static Web App hostname
                        new EnvironmentVarArgs
                        {
                            Name = "Cors__AllowedOrigins",
                            Value = staticWebApp.DefaultHostname.Apply(swaHost =>
                                $"https://{swaHost},http://localhost:3000")
                        }
                    }
                }
            },
            Scale = new ScaleArgs
            {
                MinReplicas = 0,
                MaxReplicas = 3,
                Rules = new[]
                {
                    new ScaleRuleArgs
                    {
                        Name = "http-scaling",
                        Http = new HttpScaleRuleArgs
                        {
                            Metadata = new InputMap<string>
                            {
                                { "concurrentRequests", "10" }
                            }
                        }
                    }
                }
            }
        },
        WorkloadProfileName = "Consumption",
        Tags = new InputMap<string>
        {
            { "Environment", environment },
            { "Project", "HotshotLogistics" }
        }
    }, new CustomResourceOptions
    {
        // Ensure role assignments are complete before creating the Container App
        DependsOn = { acrPullRoleAssignment, appConfigRoleAssignment },
        IgnoreChanges = new List<string> { "template.containers[*].image" }
    });

    // Export outputs
    // These outputs can be consumed by CI/CD pipelines via: pulumi stack output <name>
    return new Dictionary<string, object?>
    {
        // Resource Group
        ["resourceGroupName"] = resourceGroup.Name,
        
        // Container Registry (ACR)
        ["containerRegistryName"] = registry.Name,
        ["containerRegistryLoginServer"] = registry.LoginServer,
        
        // Container App
        ["containerAppName"] = containerApp.Name,
        ["containerAppUrl"] = containerApp.Configuration.Apply(c => c!.Ingress!.Fqdn),
        ["containerAppFullUrl"] = containerApp.Configuration.Apply(c => $"https://{c!.Ingress!.Fqdn}"),
        
        // Container Image (for CI/CD to know what to push)
        ["containerImageName"] = imageName,
        ["containerImageTag"] = imageTag,
        ["containerImageFullPath"] = registry.LoginServer.Apply(server => $"{server}/{imageName}:{imageTag}"),
        
        // Job Details
        ["migrationJobName"] = migrationJob.Name,
        ["migrationJobImageName"] = jobImageName,
        ["migrationJobImageFullPath"] = registry.LoginServer.Apply(server => $"{server}/{jobImageName}:{jobImageTag}"),

        // Managed Identity
        ["containerAppIdentityId"] = containerAppIdentity.Id,
        ["containerAppIdentityClientId"] = containerAppIdentity.ClientId,
        ["containerAppPrincipalId"] = containerAppIdentity.PrincipalId,
        
        // Key Vault
        ["keyVaultName"] = keyVault.Name,
        ["keyVaultUri"] = keyVault.Properties.Apply(p => p.VaultUri),
        
        // App Configuration
        ["appConfigName"] = appConfig.Name,
        ["appConfigEndpoint"] = appConfig.Endpoint,
        
        // Static Web App
        ["staticWebAppName"] = staticWebApp.Name,
        ["staticWebAppUrl"] = staticWebApp.DefaultHostname,
        ["staticWebAppFullUrl"] = staticWebApp.DefaultHostname.Apply(h => $"https://{h}"),
        
        // Application Insights (secrets)
        ["appInsightsInstrumentationKey"] = Output.CreateSecret(appInsightsInstrumentationKey),
        ["appInsightsConnectionString"] = Output.CreateSecret(appInsightsConnectionString),
        
        // SQL Server
        ["sqlServerFqdn"] = sqlServer.FullyQualifiedDomainName,
        ["databaseName"] = database.Name,
        
        // Log Analytics
        ["logAnalyticsWorkspaceId"] = workspace.CustomerId
    };
});
