<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>a562df9b-74fa-48b9-adfc-379cdc5868a7</UserSecretsId>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="HotshotLogistics.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="8.4.0" />
    <PackageReference Include="Microsoft.Graph" Version="5.94.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="3.14.1" />
    <PackageReference Include="Microsoft.Identity.Web.MicrosoftGraph" Version="3.14.1" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.32.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\2-Application\HotshotLogistics.Application\HotshotLogistics.Application.csproj" />
    <ProjectReference Include="..\..\3-Domain\HotshotLogistics.Contracts\HotshotLogistics.Contracts.csproj" />
    <ProjectReference Include="..\..\3-Domain\HotshotLogistics.Domain\HotshotLogistics.Domain.csproj" />
    <ProjectReference Include="..\..\4-Persistence\HotshotLogistics.Data\HotshotLogistics.Data.csproj" />
    <ProjectReference Include="..\..\0-Base\HotshotLogistics.Core\HotshotLogistics.Core.csproj" />
  </ItemGroup>
  
</Project>
